### ISSUE TITLE
Error with ansible 2.5.3

### ISSUE THREAD

**Issue by Prodian0013** [larsks/ansible-assertive#4]
`ERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'add_representer'`

`ansible 2.5.3
  config file = /root/code/tfplenum-integration-testing/playbooks/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
`

**Comment by larsks** [comment]
I have just spent some time making this plugin work with Ansible 2.9.2 and Python 3. I'm probably not going to worry about backports to earlier versions.
